"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Находим числа Фибоначчи классическим способом и проверяем их на чётность

END = 4_000_000
num1 = 1
num2 = 2
total = 0

while num1 <= END:
    if not num2 % 2:
        total += num2
    
    num1, num2 = num2, num1 + num2

print(total)
